version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.3
